/*
 * File:   Defaults.h
 * Author: arseniuss
 *
 */

#ifndef DEFAULTS_H
#define	DEFAULTS_H

#define MAX_PLAYER_COUNT		4
#define MAX_MESSAGE_SIZE		256
#define MAX_USERNAME_LEN		15

#define DEFAULT_GAME_WIDTH		80
#define DEFAULT_GAME_HEIGHT		20
#define DEFAULT_GAME_SPEED		5
#define DEFAULT_FOOD_AMOUNT		2
#define DEFAULT_SCORE_LIMIT		15
#define DEFAULT_TIME_LIMIT		2
#define DEFAULT_PLAYER_COUNT		4

#define DEFAULT_SNAKE_INITIAL_SIZE	3

#define DEFAULT_SERVER_ADDRESS		"127.0.0.1"
#define DEFAULT_SERVER_PORT_NO		65342

#endif	/* DEFAULTS_H */

